disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - trailing_whitespace
  - nesting
  - implicit_getter
  - void_return
  - large_tuple
  - file_length
  - statement_position
  - line_length
  - unused_optional_binding
  - redundant_discardable_let
  - todo
  - identifier_name
  - function_body_length
  - legacy_hashing
  - force_cast

included: # paths to include during linting. `--path` is ignored if present.
  - Sources

cyclomatic_complexity:
  warning: 50
  error: 50